### ISSUE TITLE
Include "supported-by-me" attribute on proposal payloads

### ISSUE THREAD

**Issue by oliverbarnes** [participateapp/api#27]
Possible values: `"true"` | `"false"`

Based on whether the current participant supports the proposal.

Payloads to be updated: proposal listing, proposal details and included proposal in newly created support resource

**Comment by oliverbarnes** [comment]
For https://github.com/oliverbarnes/participate/issues/17

**Comment by ThomasWeiser** [comment]
Related: currently a participant can support the same proposal multiple times. Should probably delete previous support id or reject a support request if support is already present.
